package patches.projects

import jetbrains.buildServer.configs.kotlin.v2019_2.*
import jetbrains.buildServer.configs.kotlin.v2019_2.Project
import jetbrains.buildServer.configs.kotlin.v2019_2.projectFeatures.GitHubIssueTracker
import jetbrains.buildServer.configs.kotlin.v2019_2.projectFeatures.githubIssues
import jetbrains.buildServer.configs.kotlin.v2019_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the root project
accordingly, and delete the patch script.
*/
changeProject(DslContext.projectId) {
    params {
        expect {
            text("git_branch_spec", "+:refs/heads/(FG_*)", label = "The branch specification of the repository", description = "By default all main branches are build by the configuration. Modify this value to adapt the branches build.", display = ParameterDisplay.HIDDEN, allowEmpty = true)
        }
        update {
            text("git_branch_spec", """
                +:refs/heads/(FG_*)
                +:refs/heads/(NG_*)
            """.trimIndent(), label = "The branch specification of the repository", description = "By default all main branches are build by the configuration. Modify this value to adapt the branches build.", display = ParameterDisplay.HIDDEN, allowEmpty = true)
        }
    }

    features {
        val feature1 = find<GitHubIssueTracker> {
            githubIssues {
                id = "NeoGradle__IssueTracker"
                displayName = "NeoForged/NeoGradle"
                repositoryURL = "https://github.com/NeoForged/NeoGradle"
            }
        }
        feature1.apply {
        }
    }
}
