plugins {
    id 'java-library'
}

repositories {
    maven {
        name 'Gradle Releases'
        url 'https://repo.gradle.org/gradle/libs-releases/'
    }
}

java {
    registerFeature("gradle814") {
        usingSourceSet(sourceSets.create("gradle814"))
        capability(project.group, project.name + "-impl", project.version)
    }
    registerFeature("gradle813") {
        usingSourceSet(sourceSets.create("gradle813"))
        capability(project.group, project.name + "-impl", project.version)
    }
}

dependencies {
    gradle813CompileOnly gradleApi()
    gradle813Api (project) {
        capabilities {
            requireCapability('net.neoforged.gradle:eclipse')
        }
    }

    gradle814CompileOnly ('org.gradle.experimental:gradle-public-api:8.14') {
        capabilities {
            requireCapability("org.gradle.experimental:gradle-public-api-internal")
        }
    }
    gradle814Api (project) {
        capabilities {
            requireCapability('net.neoforged.gradle:eclipse')
        }
    }
}

Attribute<String> GRADLE_API_VERSION_ATTRIBUTE = Attribute.of("org.gradle.plugin.api-version", String.class);
configurations {
    gradle813ApiElements {
        attributes {
            attribute(GRADLE_API_VERSION_ATTRIBUTE, "8.13")
        }
    }

    gradle813RuntimeElements {
        attributes {
            attribute(GRADLE_API_VERSION_ATTRIBUTE, "8.13")
        }
    }
    gradle814ApiElements {
        attributes {
            attribute(GRADLE_API_VERSION_ATTRIBUTE, "8.14")
        }
    }

    gradle814RuntimeElements {
        attributes {
            attribute(GRADLE_API_VERSION_ATTRIBUTE, "8.14")
        }
    }
}

AdhocComponentWithVariants javaComponent = (AdhocComponentWithVariants) project.components.findByName("java")
javaComponent.addVariantsFromConfiguration(configurations.gradle814ApiElements) {}
javaComponent.addVariantsFromConfiguration(configurations.gradle814RuntimeElements) {
    it.mapToMavenScope('runtime')
}
javaComponent.addVariantsFromConfiguration(configurations.gradle813ApiElements) {}
javaComponent.addVariantsFromConfiguration(configurations.gradle813RuntimeElements) {
    it.mapToMavenScope('runtime')
}