plugins {
   id 'net.neoforged.gradle.userdev'
} 


            java {
                toolchain {
                    languageVersion = JavaLanguageVersion.of(21)
                }
            }
            
            dependencies {
                implementation 'net.neoforged:neoforge:+'
                implementation project(':api')
            }
            
            runs {
                client {
                    modSource project(':api').sourceSets.main
                }
            }
            