plugins {
   id 'net.neoforged.gradle.userdev'
} 


            java {
                toolchain {
                    languageVersion = JavaLanguageVersion.of(21)
                }
            }
            
            repositories {
                mavenLocal()
            }
                        
            dependencies {
                implementation 'net.neoforged:neoforge:21.10.64-fix-issue-2848-binpatches-userdev'
            }
            